### ISSUE TITLE
Small error on documentation

### ISSUE THREAD

**Issue by VincentLoy** [milligram/milligram-less#1]
Hi there ! I think that there is a (very) small error on grid system documentation.
As you can see on the following screenshot, `column` class is duplicated. 

![milligram-small-error](https://cloud.githubusercontent.com/assets/7996741/12303537/205ce7a6-ba2b-11e5-8608-62912a19db9a.png)

**Comment by VincentLoy** [comment]
mmh I wanted to post this issue here https://github.com/milligram/milligram.github.io

**Comment by cjpatoilo** [comment]
Hi @VincentLoy  
This went unnoticed, thanks for the info.
