### ISSUE TITLE
Problema na documentação

### ISSUE THREAD

**Issue by luiguild** [milligram/milligram-less#2]
Tanto na versão -less ou na versão -css a documentação de tipografia aponta que o H1 é:
h1 {
  font-size: 5rem;
  letter-spacing: -0.1rem;
  line-height: 1.2;
}

porém no código:
h1 {
  font-size: 4rem;
  letter-spacing: -0.1rem;
  line-height: 1.2;
}

**Comment by cjpatoilo** [comment]
Olá @luiguild 
Note, esse valor é o inicial (mobile first). Para telas maiores o valor é o que está descrito. 

![image](https://cloud.githubusercontent.com/assets/1542831/12696004/fc7544f4-c73c-11e5-96c3-04a25027a356.png)

![image](https://cloud.githubusercontent.com/assets/1542831/12695969/28347656-c73c-11e5-86be-c5da7b5b22db.png)

**Comment by luiguild** [comment]
:smile: parabéns pelo projeto!
