### ISSUE TITLE
Left over !default's from milligram's main SASS code.

### ISSUE THREAD

**Issue by LanetheGreat** [milligram/milligram-less#4]
### Version info:
Affects milligram-less versions 1.2.0 and up.

### Expected behavior
Expect `npm run less` to successfully compile milligram-less.

### Actual behavior
Command errors with:
```
NameError: variable @color-secondary is undefined in 'milligram-less\src\_Base.less' on line 21, column 9:
20 body {
21      color: @color-secondary;
22      font-family: 'Roboto', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
```
### Reason
It looks like back when you guys released v1.2.0 in commit [f3acaf863f7012baf8c206cd3dfe3e5ec19b70c3](https://github.com/milligram/milligram-less/commit/f3acaf863f7012baf8c206cd3dfe3e5ec19b70c3) you forked the source from the main project ([milligram](https://github.com/milligram/milligram)'s SASS) but it looks like you guys left in the [`!default` at the end of each variable in `_Color.less`.](https://github.com/milligram/milligram-less/commit/f3acaf863f7012baf8c206cd3dfe3e5ec19b70c3#diff-0843a984fec06d8df12b4de0c145e0ca) Which is technically not valid LESS syntax and causing `lessc` to silently ignore `_Color.less` leaving all its variables undefined and leading to the error above. Removing said `!default`'s fixes the build process.

I'm currently using milligram-less to unit test a custom compiler invoking less in a [forked project](https://github.com/LanetheGreat/electron-compilers) I'm using. Would it be possible for you guys to remove the `!default`'s during the forking/build process that you guys have, and maybe make a patch on npm for it like v1.3.1?

**Comment by cjpatoilo** [comment]
@LanetheGreat good call. 
Let me know if you can help me with this.
